version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sas_app
    volumes:
      - .:/app
    # Mantém o container rodando
    tty: true
    stdin_open: true
    ports:
      - "8000:8000"
      - "5173:5173" # Porta padrão do Vite/React
